### ISSUE TITLE
Doesn't work with new v4 API

### ISSUE THREAD

**Issue by frankysan** [Miicroo/ha-vasttrafik#1]
Neither this nor the core vasttrafik sensor works with the new v4 API. The old API will be shutdown in a few months.

**Comment by Miicroo** [comment]
@frankysan Thank you for reporting! I have referenced it in the core library, but it does look a bit unmaintained (last commit 6pm  years ago). Will try to create a PR in that repo first to see if it is solvable :)

**Comment by Miicroo** [comment]
@frankysan I have found the new APIs and portal and looking through them to update the core library. Did you find a final date for the old API? Have been looking through their documentation but haven't been able to find anything

**Comment by frankysan** [comment]
@Miicroo The relevant information can be found here: https://developer.vasttrafik.se/news/3

**Comment by Miicroo** [comment]
Fixed in HA 2023.11
